version: "3"

services:
    db:
        image: my-mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: password
    app:
        build: .
        ports:
        -   "80:80"
        depends_on:
            - db
volumes:
    db_data:
